import { copyFile } from "node:fs/promises";
import { builtinModules } from "node:module";
import { resolve } from "node:path";
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
	...builtinModules.map((module) => `node:${module}`),
];

function syncObsidianBuildOutput() {
	return {
		name: "sync-obsidian-build-output",
		apply: "build" as const,
		async closeBundle() {
			await copyFile(
				resolve(__dirname, "dist/main.js"),
				resolve(__dirname, "main.js"),
			);
		},
	};
}

export default defineConfig(({ mode }) => {
	const production = mode === "production";

	return {
		plugins: [
			svelte({
				compilerOptions: {
					css: "injected",
				},
			}),
			syncObsidianBuildOutput(),
		],
		publicDir: false,
		build: {
			outDir: "dist",
			emptyOutDir: true,
			sourcemap: production ? false : "inline",
			minify: production,
			lib: {
				entry: resolve(__dirname, "src/main.ts"),
				formats: ["cjs"],
				fileName: () => "main.js",
			},
			rollupOptions: {
				external,
				output: {
					banner,
					entryFileNames: "main.js",
					exports: "default",
					format: "cjs",
				},
			},
		},
	};
});
